-- SideRoom Supabase Full Setup Bundle
-- Generated automatically by scripts/build-supabase-bundle.js
-- Do not edit this file by hand. Edit the ordered files in supabase/migrations instead.
--
-- Migration order included in this bundle:
-- 1. 20260323_000001_initial_schema.sql
-- 2. 20260323_000002_public_queries.sql
-- 3. 20260323_000003_search_and_safety.sql
-- 4. 20260323_000004_notifications.sql
-- 5. 20260323_000005_moderation_tools.sql
-- 6. 20260323_000006_personal_activity.sql
-- 7. 20260323_000007_post_resolution.sql
-- 8. 20260327_000008_account_deletion.sql

-- BEGIN MIGRATION: 20260323_000001_initial_schema.sql
create extension if not exists pgcrypto;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  auth_provider text not null default 'email',
  status text not null default 'active' check (status in ('active', 'suspended', 'banned')),
  role text not null default 'user' check (role in ('user', 'moderator', 'admin')),
  disclaimer_accepted_at timestamptz,
  onboarding_completed_at timestamptz,
  last_seen_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.app_is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users
    where id = auth.uid()
      and role in ('moderator', 'admin')
  );
$$;

create table if not exists public.user_profiles (
  user_id uuid primary key references public.users (id) on delete cascade,
  handle text not null,
  bio text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint handle_format check (handle ~ '^[a-z0-9_]{3,24}$')
);

create unique index if not exists user_profiles_handle_unique
  on public.user_profiles (lower(handle));

create table if not exists public.topics (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text not null,
  created_at timestamptz not null default timezone('utc', now()),
  is_active boolean not null default true
);

create table if not exists public.topic_follows (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete cascade,
  topic_id uuid not null references public.topics (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, topic_id)
);

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete cascade,
  topic_id uuid not null references public.topics (id) on delete restrict,
  title text not null check (char_length(title) between 6 and 160),
  body text,
  post_type text not null check (post_type in ('question', 'advice_request', 'poll', 'story', 'update')),
  is_anonymous boolean not null default false,
  status text not null default 'open' check (status in ('open', 'resolved', 'locked', 'removed')),
  moderation_status text not null default 'clean' check (moderation_status in ('clean', 'flagged', 'under_review', 'removed')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  parent_comment_id uuid references public.comments (id) on delete cascade,
  body text not null check (char_length(body) between 1 and 5000),
  is_deleted boolean not null default false,
  moderation_status text not null default 'clean' check (moderation_status in ('clean', 'flagged', 'under_review', 'removed')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.reactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete cascade,
  target_type text not null check (target_type in ('post', 'comment')),
  target_id uuid not null,
  reaction_type text not null check (reaction_type in ('upvote', 'downvote', 'helpful')),
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, target_type, target_id, reaction_type)
);

create table if not exists public.saves (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete cascade,
  post_id uuid not null references public.posts (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, post_id)
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_user_id uuid not null references public.users (id) on delete cascade,
  target_type text not null check (target_type in ('post', 'comment', 'user')),
  target_id uuid not null,
  reason text not null,
  details text,
  status text not null default 'open' check (status in ('open', 'reviewed', 'actioned', 'dismissed')),
  created_at timestamptz not null default timezone('utc', now()),
  reviewed_by uuid references public.users (id) on delete set null,
  reviewed_at timestamptz
);

create table if not exists public.moderation_actions (
  id uuid primary key default gen_random_uuid(),
  moderator_user_id uuid not null references public.users (id) on delete restrict,
  target_type text not null,
  target_id uuid not null,
  action_type text not null,
  reason text not null,
  notes text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete cascade,
  type text not null,
  entity_type text not null,
  entity_id uuid not null,
  is_read boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.blocked_users (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete cascade,
  blocked_user_id uuid not null references public.users (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, blocked_user_id),
  constraint blocked_users_no_self_block check (user_id <> blocked_user_id)
);

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email, auth_provider)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_app_meta_data ->> 'provider', 'email')
  )
  on conflict (id) do update
    set email = excluded.email,
        auth_provider = excluded.auth_provider,
        updated_at = timezone('utc', now());

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_auth_user();

create or replace function public.protect_user_account_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() = old.id and not public.app_is_staff() then
    if new.email <> old.email
      or new.auth_provider <> old.auth_provider
      or new.role <> old.role
      or new.status <> old.status then
      raise exception 'You cannot change privileged account fields directly.';
    end if;
  end if;

  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists users_updated_at on public.users;
create trigger users_updated_at
before update on public.users
for each row
execute procedure public.protect_user_account_update();

drop trigger if exists user_profiles_updated_at on public.user_profiles;
create trigger user_profiles_updated_at
before update on public.user_profiles
for each row
execute procedure public.touch_updated_at();

drop trigger if exists posts_updated_at on public.posts;
create trigger posts_updated_at
before update on public.posts
for each row
execute procedure public.touch_updated_at();

drop trigger if exists comments_updated_at on public.comments;
create trigger comments_updated_at
before update on public.comments
for each row
execute procedure public.touch_updated_at();

create or replace function public.complete_onboarding(input_handle text, input_topic_ids uuid[])
returns public.user_profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_handle text;
  selected_topic_count integer;
  valid_topic_count integer;
  output_profile public.user_profiles;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  normalized_handle := lower(trim(input_handle));
  selected_topic_count := coalesce(array_length(input_topic_ids, 1), 0);

  if normalized_handle !~ '^[a-z0-9_]{3,24}$' then
    raise exception 'Handle must be 3 to 24 characters using letters, numbers, or underscores.';
  end if;

  if selected_topic_count < 3 or selected_topic_count > 5 then
    raise exception 'Choose between 3 and 5 topics.';
  end if;

  select count(*)
    into valid_topic_count
  from public.topics
  where id = any(input_topic_ids)
    and is_active = true;

  if valid_topic_count <> selected_topic_count then
    raise exception 'Selected topics must exist and be active.';
  end if;

  insert into public.user_profiles (user_id, handle)
  values (auth.uid(), normalized_handle)
  on conflict (user_id) do update
    set handle = excluded.handle,
        updated_at = timezone('utc', now())
  returning *
    into output_profile;

  delete from public.topic_follows
  where user_id = auth.uid();

  insert into public.topic_follows (user_id, topic_id)
  select auth.uid(), selected_topics.topic_id
  from (
    select distinct unnest(input_topic_ids) as topic_id
  ) as selected_topics;

  update public.users
    set disclaimer_accepted_at = coalesce(disclaimer_accepted_at, timezone('utc', now())),
        onboarding_completed_at = timezone('utc', now()),
        last_seen_at = timezone('utc', now())
  where id = auth.uid();

  return output_profile;
end;
$$;

create or replace function public.touch_last_seen()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is not null then
    update public.users
      set last_seen_at = timezone('utc', now())
    where id = auth.uid();
  end if;
end;
$$;

alter table public.users enable row level security;
alter table public.user_profiles enable row level security;
alter table public.topics enable row level security;
alter table public.topic_follows enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.reactions enable row level security;
alter table public.saves enable row level security;
alter table public.reports enable row level security;
alter table public.moderation_actions enable row level security;
alter table public.notifications enable row level security;
alter table public.blocked_users enable row level security;

alter table public.users force row level security;
alter table public.user_profiles force row level security;
alter table public.topics force row level security;
alter table public.topic_follows force row level security;
alter table public.posts force row level security;
alter table public.comments force row level security;
alter table public.reactions force row level security;
alter table public.saves force row level security;
alter table public.reports force row level security;
alter table public.moderation_actions force row level security;
alter table public.notifications force row level security;
alter table public.blocked_users force row level security;

create policy "users_select_own_or_staff"
on public.users
for select
to authenticated
using (auth.uid() = id or public.app_is_staff());

create policy "users_update_own_or_staff"
on public.users
for update
to authenticated
using (auth.uid() = id or public.app_is_staff())
with check (auth.uid() = id or public.app_is_staff());

create policy "profiles_select_authenticated"
on public.user_profiles
for select
to authenticated
using (true);

create policy "profiles_insert_own_or_staff"
on public.user_profiles
for insert
to authenticated
with check (auth.uid() = user_id or public.app_is_staff());

create policy "profiles_update_own_or_staff"
on public.user_profiles
for update
to authenticated
using (auth.uid() = user_id or public.app_is_staff())
with check (auth.uid() = user_id or public.app_is_staff());

create policy "topics_select_active"
on public.topics
for select
to authenticated
using (is_active = true);

create policy "topic_follows_select_own_or_staff"
on public.topic_follows
for select
to authenticated
using (auth.uid() = user_id or public.app_is_staff());

create policy "topic_follows_insert_own_or_staff"
on public.topic_follows
for insert
to authenticated
with check (auth.uid() = user_id or public.app_is_staff());

create policy "topic_follows_delete_own_or_staff"
on public.topic_follows
for delete
to authenticated
using (auth.uid() = user_id or public.app_is_staff());

create policy "posts_select_own_or_staff_only"
on public.posts
for select
to authenticated
using (auth.uid() = user_id or public.app_is_staff());

create policy "posts_insert_own"
on public.posts
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "posts_update_own_or_staff"
on public.posts
for update
to authenticated
using (auth.uid() = user_id or public.app_is_staff())
with check (auth.uid() = user_id or public.app_is_staff());

create policy "posts_delete_own_or_staff"
on public.posts
for delete
to authenticated
using (auth.uid() = user_id or public.app_is_staff());

create policy "comments_select_own_or_staff_only"
on public.comments
for select
to authenticated
using (auth.uid() = user_id or public.app_is_staff());

create policy "comments_insert_own"
on public.comments
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "comments_update_own_or_staff"
on public.comments
for update
to authenticated
using (auth.uid() = user_id or public.app_is_staff())
with check (auth.uid() = user_id or public.app_is_staff());

create policy "comments_delete_own_or_staff"
on public.comments
for delete
to authenticated
using (auth.uid() = user_id or public.app_is_staff());

create policy "reactions_select_own_or_staff"
on public.reactions
for select
to authenticated
using (auth.uid() = user_id or public.app_is_staff());

create policy "reactions_insert_own"
on public.reactions
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "reactions_delete_own_or_staff"
on public.reactions
for delete
to authenticated
using (auth.uid() = user_id or public.app_is_staff());

create policy "saves_select_own_or_staff"
on public.saves
for select
to authenticated
using (auth.uid() = user_id or public.app_is_staff());

create policy "saves_insert_own"
on public.saves
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "saves_delete_own_or_staff"
on public.saves
for delete
to authenticated
using (auth.uid() = user_id or public.app_is_staff());

create policy "reports_select_reporter_or_staff"
on public.reports
for select
to authenticated
using (auth.uid() = reporter_user_id or public.app_is_staff());

create policy "reports_insert_reporter"
on public.reports
for insert
to authenticated
with check (auth.uid() = reporter_user_id);

create policy "reports_update_staff"
on public.reports
for update
to authenticated
using (public.app_is_staff())
with check (public.app_is_staff());

create policy "moderation_actions_staff_only"
on public.moderation_actions
for all
to authenticated
using (public.app_is_staff())
with check (public.app_is_staff());

create policy "notifications_select_own_or_staff"
on public.notifications
for select
to authenticated
using (auth.uid() = user_id or public.app_is_staff());

create policy "notifications_update_own_or_staff"
on public.notifications
for update
to authenticated
using (auth.uid() = user_id or public.app_is_staff())
with check (auth.uid() = user_id or public.app_is_staff());

create policy "blocked_users_select_own_or_staff"
on public.blocked_users
for select
to authenticated
using (auth.uid() = user_id or public.app_is_staff());

create policy "blocked_users_insert_own"
on public.blocked_users
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "blocked_users_delete_own_or_staff"
on public.blocked_users
for delete
to authenticated
using (auth.uid() = user_id or public.app_is_staff());

revoke all on table public.users from anon, authenticated;
revoke all on table public.user_profiles from anon, authenticated;
revoke all on table public.topics from anon, authenticated;
revoke all on table public.topic_follows from anon, authenticated;
revoke all on table public.posts from anon, authenticated;
revoke all on table public.comments from anon, authenticated;
revoke all on table public.reactions from anon, authenticated;
revoke all on table public.saves from anon, authenticated;
revoke all on table public.reports from anon, authenticated;
revoke all on table public.moderation_actions from anon, authenticated;
revoke all on table public.notifications from anon, authenticated;
revoke all on table public.blocked_users from anon, authenticated;

grant select, update on public.users to authenticated;
grant select, insert, update on public.user_profiles to authenticated;
grant select on public.topics to authenticated;
grant select, insert, delete on public.topic_follows to authenticated;
grant select, insert, update, delete on public.posts to authenticated;
grant select, insert, update, delete on public.comments to authenticated;
grant select, insert, delete on public.reactions to authenticated;
grant select, insert, delete on public.saves to authenticated;
grant select, insert, update on public.reports to authenticated;
grant select, insert on public.moderation_actions to authenticated;
grant select, update on public.notifications to authenticated;
grant select, insert, delete on public.blocked_users to authenticated;

revoke all on function public.complete_onboarding(text, uuid[]) from public;
revoke all on function public.touch_last_seen() from public;
grant execute on function public.complete_onboarding(text, uuid[]) to authenticated;
grant execute on function public.touch_last_seen() to authenticated;

insert into public.topics (slug, name, description)
values
  ('work-career', 'Work & Career', 'Questions about work, burnout, promotions, bosses, and changing direction.'),
  ('relationships-dating', 'Relationships & Dating', 'Dating, breakups, commitment, boundaries, and communication.'),
  ('money', 'Money', 'Budgeting, debt, pay, savings, and money stress.'),
  ('friends-family', 'Friends & Family', 'Friendships, family tension, and building support systems.'),
  ('mental-load-stress', 'Mental Load & Stress', 'Stress, emotional load, burnout, and daily pressure.'),
  ('life-decisions', 'Life Decisions', 'Big tradeoffs, uncertainty, identity questions, and crossroads moments.'),
  ('school-early-career', 'School & Early Career', 'School, first jobs, internships, and figuring out the start of adult life.'),
  ('moving-city-life', 'Moving & City Life', 'Relocating, roommates, neighborhoods, and starting over somewhere new.')
on conflict (slug) do update
  set name = excluded.name,
      description = excluded.description,
      is_active = true;
-- END MIGRATION: 20260323_000001_initial_schema.sql

-- BEGIN MIGRATION: 20260323_000002_public_queries.sql
create index if not exists posts_feed_idx
  on public.posts (topic_id, moderation_status, status, created_at desc);

create index if not exists comments_post_lookup_idx
  on public.comments (post_id, moderation_status, is_deleted, created_at);

create index if not exists reactions_target_lookup_idx
  on public.reactions (target_type, target_id, reaction_type);

drop policy if exists "profiles_select_authenticated" on public.user_profiles;

create policy "profiles_select_own_or_staff"
on public.user_profiles
for select
to authenticated
using (auth.uid() = user_id or public.app_is_staff());

create or replace function public.get_feed_posts(
  input_topic_id uuid default null,
  input_limit integer default 25,
  input_offset integer default 0
)
returns table (
  post_id uuid,
  topic_id uuid,
  topic_name text,
  topic_slug text,
  title text,
  body_preview text,
  post_type text,
  status text,
  is_anonymous boolean,
  created_at timestamptz,
  comment_count bigint,
  helpful_count bigint,
  net_votes bigint,
  viewer_has_saved boolean,
  viewer_vote text,
  viewer_marked_helpful boolean,
  author_label text,
  author_trust_hint text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id as post_id,
    t.id as topic_id,
    t.name as topic_name,
    t.slug as topic_slug,
    p.title,
    case
      when p.body is null or btrim(p.body) = '' then null
      when char_length(btrim(p.body)) <= 220 then btrim(p.body)
      else left(btrim(p.body), 217) || '...'
    end as body_preview,
    p.post_type,
    p.status,
    p.is_anonymous,
    p.created_at,
    coalesce(comment_counts.comment_count, 0) as comment_count,
    coalesce(helpful_counts.helpful_count, 0) as helpful_count,
    coalesce(vote_counts.net_votes, 0) as net_votes,
    coalesce(save_state.viewer_has_saved, false) as viewer_has_saved,
    vote_state.viewer_vote,
    coalesce(helpful_state.viewer_marked_helpful, false) as viewer_marked_helpful,
    case
      when p.is_anonymous then 'Anonymous'
      else up.handle
    end as author_label,
    case
      when age(timezone('utc', now()), u.created_at) < interval '30 days' then 'Member since this month'
      else 'Community contributor'
    end as author_trust_hint
  from public.posts p
  join public.topics t
    on t.id = p.topic_id
   and t.is_active = true
  join public.users u
    on u.id = p.user_id
   and u.status = 'active'
  join public.user_profiles up
    on up.user_id = p.user_id
  left join public.topic_follows tf
    on tf.topic_id = p.topic_id
   and tf.user_id = auth.uid()
  left join lateral (
    select count(*)::bigint as comment_count
    from public.comments c
    where c.post_id = p.id
      and c.is_deleted = false
      and c.moderation_status = 'clean'
  ) as comment_counts on true
  left join lateral (
    select count(*)::bigint as helpful_count
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.reaction_type = 'helpful'
  ) as helpful_counts on true
  left join lateral (
    select
      coalesce(sum(case when r.reaction_type = 'upvote' then 1 when r.reaction_type = 'downvote' then -1 else 0 end), 0)::bigint as net_votes
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.reaction_type in ('upvote', 'downvote')
  ) as vote_counts on true
  left join lateral (
    select true as viewer_has_saved
    from public.saves s
    where s.post_id = p.id
      and s.user_id = auth.uid()
    limit 1
  ) as save_state on true
  left join lateral (
    select r.reaction_type as viewer_vote
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.user_id = auth.uid()
      and r.reaction_type in ('upvote', 'downvote')
    limit 1
  ) as vote_state on true
  left join lateral (
    select true as viewer_marked_helpful
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.user_id = auth.uid()
      and r.reaction_type = 'helpful'
    limit 1
  ) as helpful_state on true
  where auth.uid() is not null
    and exists (
      select 1
      from public.users viewer
      where viewer.id = auth.uid()
        and viewer.status = 'active'
        and viewer.disclaimer_accepted_at is not null
        and viewer.onboarding_completed_at is not null
    )
    and p.moderation_status = 'clean'
    and p.status <> 'removed'
    and (input_topic_id is null or p.topic_id = input_topic_id)
  order by
    case when tf.user_id is not null then 1 else 0 end desc,
    case when p.status = 'open' then 1 else 0 end desc,
    coalesce(helpful_counts.helpful_count, 0) desc,
    coalesce(comment_counts.comment_count, 0) desc,
    p.created_at desc
  limit greatest(1, least(coalesce(input_limit, 25), 50))
  offset greatest(coalesce(input_offset, 0), 0);
$$;

create or replace function public.get_post_detail(input_post_id uuid)
returns table (
  post_id uuid,
  topic_id uuid,
  topic_name text,
  topic_slug text,
  title text,
  body text,
  post_type text,
  status text,
  is_anonymous boolean,
  created_at timestamptz,
  updated_at timestamptz,
  comment_count bigint,
  helpful_count bigint,
  net_votes bigint,
  viewer_has_saved boolean,
  viewer_vote text,
  viewer_marked_helpful boolean,
  viewer_is_owner boolean,
  author_label text,
  author_trust_hint text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id as post_id,
    t.id as topic_id,
    t.name as topic_name,
    t.slug as topic_slug,
    p.title,
    p.body,
    p.post_type,
    p.status,
    p.is_anonymous,
    p.created_at,
    p.updated_at,
    coalesce(comment_counts.comment_count, 0) as comment_count,
    coalesce(helpful_counts.helpful_count, 0) as helpful_count,
    coalesce(vote_counts.net_votes, 0) as net_votes,
    coalesce(save_state.viewer_has_saved, false) as viewer_has_saved,
    vote_state.viewer_vote,
    coalesce(helpful_state.viewer_marked_helpful, false) as viewer_marked_helpful,
    p.user_id = auth.uid() as viewer_is_owner,
    case
      when p.is_anonymous then 'Anonymous'
      else up.handle
    end as author_label,
    case
      when age(timezone('utc', now()), u.created_at) < interval '30 days' then 'Member since this month'
      else 'Community contributor'
    end as author_trust_hint
  from public.posts p
  join public.topics t
    on t.id = p.topic_id
   and t.is_active = true
  join public.users u
    on u.id = p.user_id
   and u.status = 'active'
  join public.user_profiles up
    on up.user_id = p.user_id
  left join lateral (
    select count(*)::bigint as comment_count
    from public.comments c
    where c.post_id = p.id
      and c.is_deleted = false
      and c.moderation_status = 'clean'
  ) as comment_counts on true
  left join lateral (
    select count(*)::bigint as helpful_count
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.reaction_type = 'helpful'
  ) as helpful_counts on true
  left join lateral (
    select
      coalesce(sum(case when r.reaction_type = 'upvote' then 1 when r.reaction_type = 'downvote' then -1 else 0 end), 0)::bigint as net_votes
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.reaction_type in ('upvote', 'downvote')
  ) as vote_counts on true
  left join lateral (
    select true as viewer_has_saved
    from public.saves s
    where s.post_id = p.id
      and s.user_id = auth.uid()
    limit 1
  ) as save_state on true
  left join lateral (
    select r.reaction_type as viewer_vote
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.user_id = auth.uid()
      and r.reaction_type in ('upvote', 'downvote')
    limit 1
  ) as vote_state on true
  left join lateral (
    select true as viewer_marked_helpful
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.user_id = auth.uid()
      and r.reaction_type = 'helpful'
    limit 1
  ) as helpful_state on true
  where auth.uid() is not null
    and exists (
      select 1
      from public.users viewer
      where viewer.id = auth.uid()
        and viewer.status = 'active'
        and viewer.disclaimer_accepted_at is not null
        and viewer.onboarding_completed_at is not null
    )
    and p.id = input_post_id
    and p.moderation_status = 'clean'
    and p.status <> 'removed';
$$;

create or replace function public.get_post_comments(input_post_id uuid)
returns table (
  comment_id uuid,
  parent_comment_id uuid,
  body text,
  created_at timestamptz,
  author_label text,
  author_trust_hint text,
  viewer_is_owner boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    c.id as comment_id,
    c.parent_comment_id,
    c.body,
    c.created_at,
    up.handle as author_label,
    case
      when age(timezone('utc', now()), u.created_at) < interval '30 days' then 'Member since this month'
      else 'Community contributor'
    end as author_trust_hint,
    c.user_id = auth.uid() as viewer_is_owner
  from public.comments c
  join public.posts p
    on p.id = c.post_id
   and p.moderation_status = 'clean'
   and p.status <> 'removed'
  join public.users u
    on u.id = c.user_id
   and u.status = 'active'
  join public.user_profiles up
    on up.user_id = c.user_id
  where auth.uid() is not null
    and exists (
      select 1
      from public.users viewer
      where viewer.id = auth.uid()
        and viewer.status = 'active'
        and viewer.disclaimer_accepted_at is not null
        and viewer.onboarding_completed_at is not null
    )
    and c.post_id = input_post_id
    and c.is_deleted = false
    and c.moderation_status = 'clean'
  order by c.created_at asc;
$$;

create or replace function public.create_post(
  input_topic_id uuid,
  input_title text,
  input_body text,
  input_post_type text,
  input_is_anonymous boolean default false
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_title text;
  normalized_body text;
  inserted_post_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  perform 1
  from public.users
  where id = auth.uid()
    and status = 'active'
    and disclaimer_accepted_at is not null
    and onboarding_completed_at is not null;

  if not found then
    raise exception 'Complete onboarding before creating posts.';
  end if;

  perform 1
  from public.topics
  where id = input_topic_id
    and is_active = true;

  if not found then
    raise exception 'Choose an active topic.';
  end if;

  normalized_title := btrim(coalesce(input_title, ''));
  normalized_body := nullif(btrim(coalesce(input_body, '')), '');

  if char_length(normalized_title) < 6 or char_length(normalized_title) > 160 then
    raise exception 'Title must be between 6 and 160 characters.';
  end if;

  if normalized_body is not null and char_length(normalized_body) > 5000 then
    raise exception 'Body must be 5000 characters or fewer.';
  end if;

  if input_post_type not in ('question', 'advice_request', 'poll', 'story', 'update') then
    raise exception 'Choose a valid post type.';
  end if;

  insert into public.posts (
    user_id,
    topic_id,
    title,
    body,
    post_type,
    is_anonymous
  )
  values (
    auth.uid(),
    input_topic_id,
    normalized_title,
    normalized_body,
    input_post_type,
    coalesce(input_is_anonymous, false)
  )
  returning id into inserted_post_id;

  return inserted_post_id;
end;
$$;

create or replace function public.create_comment(
  input_post_id uuid,
  input_body text,
  input_parent_comment_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_body text;
  inserted_comment_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  perform 1
  from public.users
  where id = auth.uid()
    and status = 'active'
    and disclaimer_accepted_at is not null
    and onboarding_completed_at is not null;

  if not found then
    raise exception 'Complete onboarding before commenting.';
  end if;

  perform 1
  from public.posts
  where id = input_post_id
    and moderation_status = 'clean'
    and status <> 'removed';

  if not found then
    raise exception 'This post is unavailable.';
  end if;

  if input_parent_comment_id is not null then
    perform 1
    from public.comments
    where id = input_parent_comment_id
      and post_id = input_post_id
      and is_deleted = false
      and moderation_status = 'clean';

    if not found then
      raise exception 'Parent comment is unavailable.';
    end if;
  end if;

  normalized_body := btrim(coalesce(input_body, ''));

  if char_length(normalized_body) = 0 or char_length(normalized_body) > 5000 then
    raise exception 'Comment must be between 1 and 5000 characters.';
  end if;

  insert into public.comments (
    post_id,
    user_id,
    parent_comment_id,
    body
  )
  values (
    input_post_id,
    auth.uid(),
    input_parent_comment_id,
    normalized_body
  )
  returning id into inserted_comment_id;

  return inserted_comment_id;
end;
$$;

create or replace function public.toggle_save_post(input_post_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  perform 1
  from public.users
  where id = auth.uid()
    and status = 'active'
    and disclaimer_accepted_at is not null
    and onboarding_completed_at is not null;

  if not found then
    raise exception 'Complete onboarding before saving posts.';
  end if;

  perform 1
  from public.posts
  where id = input_post_id
    and moderation_status = 'clean'
    and status <> 'removed';

  if not found then
    raise exception 'This post is unavailable.';
  end if;

  if exists (
    select 1
    from public.saves
    where user_id = auth.uid()
      and post_id = input_post_id
  ) then
    delete from public.saves
    where user_id = auth.uid()
      and post_id = input_post_id;

    return false;
  end if;

  insert into public.saves (user_id, post_id)
  values (auth.uid(), input_post_id)
  on conflict (user_id, post_id) do nothing;

  return true;
end;
$$;

create or replace function public.set_post_vote(
  input_post_id uuid,
  input_vote_type text default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  perform 1
  from public.users
  where id = auth.uid()
    and status = 'active'
    and disclaimer_accepted_at is not null
    and onboarding_completed_at is not null;

  if not found then
    raise exception 'Complete onboarding before voting on posts.';
  end if;

  perform 1
  from public.posts
  where id = input_post_id
    and moderation_status = 'clean'
    and status <> 'removed';

  if not found then
    raise exception 'This post is unavailable.';
  end if;

  if input_vote_type is not null and input_vote_type not in ('upvote', 'downvote') then
    raise exception 'Vote must be upvote, downvote, or null.';
  end if;

  delete from public.reactions
  where user_id = auth.uid()
    and target_type = 'post'
    and target_id = input_post_id
    and reaction_type in ('upvote', 'downvote');

  if input_vote_type is null then
    return null;
  end if;

  insert into public.reactions (user_id, target_type, target_id, reaction_type)
  values (auth.uid(), 'post', input_post_id, input_vote_type);

  return input_vote_type;
end;
$$;

create or replace function public.toggle_post_helpful(input_post_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  perform 1
  from public.users
  where id = auth.uid()
    and status = 'active'
    and disclaimer_accepted_at is not null
    and onboarding_completed_at is not null;

  if not found then
    raise exception 'Complete onboarding before marking posts helpful.';
  end if;

  perform 1
  from public.posts
  where id = input_post_id
    and moderation_status = 'clean'
    and status <> 'removed';

  if not found then
    raise exception 'This post is unavailable.';
  end if;

  if exists (
    select 1
    from public.reactions
    where user_id = auth.uid()
      and target_type = 'post'
      and target_id = input_post_id
      and reaction_type = 'helpful'
  ) then
    delete from public.reactions
    where user_id = auth.uid()
      and target_type = 'post'
      and target_id = input_post_id
      and reaction_type = 'helpful';

    return false;
  end if;

  insert into public.reactions (user_id, target_type, target_id, reaction_type)
  values (auth.uid(), 'post', input_post_id, 'helpful');

  return true;
end;
$$;

revoke all on function public.get_feed_posts(uuid, integer, integer) from public;
revoke all on function public.get_post_detail(uuid) from public;
revoke all on function public.get_post_comments(uuid) from public;
revoke all on function public.create_post(uuid, text, text, text, boolean) from public;
revoke all on function public.create_comment(uuid, text, uuid) from public;
revoke all on function public.toggle_save_post(uuid) from public;
revoke all on function public.set_post_vote(uuid, text) from public;
revoke all on function public.toggle_post_helpful(uuid) from public;

grant execute on function public.get_feed_posts(uuid, integer, integer) to authenticated;
grant execute on function public.get_post_detail(uuid) to authenticated;
grant execute on function public.get_post_comments(uuid) to authenticated;
grant execute on function public.create_post(uuid, text, text, text, boolean) to authenticated;
grant execute on function public.create_comment(uuid, text, uuid) to authenticated;
grant execute on function public.toggle_save_post(uuid) to authenticated;
grant execute on function public.set_post_vote(uuid, text) to authenticated;
grant execute on function public.toggle_post_helpful(uuid) to authenticated;
-- END MIGRATION: 20260323_000002_public_queries.sql

-- BEGIN MIGRATION: 20260323_000003_search_and_safety.sql
create or replace function public.community_viewer_ready()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users viewer
    where viewer.id = auth.uid()
      and viewer.status = 'active'
      and viewer.disclaimer_accepted_at is not null
      and viewer.onboarding_completed_at is not null
  );
$$;

create or replace function public.get_feed_posts(
  input_topic_id uuid default null,
  input_limit integer default 25,
  input_offset integer default 0
)
returns table (
  post_id uuid,
  topic_id uuid,
  topic_name text,
  topic_slug text,
  title text,
  body_preview text,
  post_type text,
  status text,
  is_anonymous boolean,
  created_at timestamptz,
  comment_count bigint,
  helpful_count bigint,
  net_votes bigint,
  viewer_has_saved boolean,
  viewer_vote text,
  viewer_marked_helpful boolean,
  author_label text,
  author_trust_hint text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id as post_id,
    t.id as topic_id,
    t.name as topic_name,
    t.slug as topic_slug,
    p.title,
    case
      when p.body is null or btrim(p.body) = '' then null
      when char_length(btrim(p.body)) <= 220 then btrim(p.body)
      else left(btrim(p.body), 217) || '...'
    end as body_preview,
    p.post_type,
    p.status,
    p.is_anonymous,
    p.created_at,
    coalesce(comment_counts.comment_count, 0) as comment_count,
    coalesce(helpful_counts.helpful_count, 0) as helpful_count,
    coalesce(vote_counts.net_votes, 0) as net_votes,
    coalesce(save_state.viewer_has_saved, false) as viewer_has_saved,
    vote_state.viewer_vote,
    coalesce(helpful_state.viewer_marked_helpful, false) as viewer_marked_helpful,
    case
      when p.is_anonymous then 'Anonymous'
      else up.handle
    end as author_label,
    case
      when age(timezone('utc', now()), u.created_at) < interval '30 days' then 'Member since this month'
      else 'Community contributor'
    end as author_trust_hint
  from public.posts p
  join public.topics t
    on t.id = p.topic_id
   and t.is_active = true
  join public.users u
    on u.id = p.user_id
   and u.status = 'active'
  join public.user_profiles up
    on up.user_id = p.user_id
  left join public.topic_follows tf
    on tf.topic_id = p.topic_id
   and tf.user_id = auth.uid()
  left join public.blocked_users bu
    on bu.user_id = auth.uid()
   and bu.blocked_user_id = p.user_id
  left join lateral (
    select count(*)::bigint as comment_count
    from public.comments c
    left join public.blocked_users comment_blocks
      on comment_blocks.user_id = auth.uid()
     and comment_blocks.blocked_user_id = c.user_id
    where c.post_id = p.id
      and c.is_deleted = false
      and c.moderation_status = 'clean'
      and comment_blocks.id is null
  ) as comment_counts on true
  left join lateral (
    select count(*)::bigint as helpful_count
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.reaction_type = 'helpful'
  ) as helpful_counts on true
  left join lateral (
    select
      coalesce(sum(case when r.reaction_type = 'upvote' then 1 when r.reaction_type = 'downvote' then -1 else 0 end), 0)::bigint as net_votes
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.reaction_type in ('upvote', 'downvote')
  ) as vote_counts on true
  left join lateral (
    select true as viewer_has_saved
    from public.saves s
    where s.post_id = p.id
      and s.user_id = auth.uid()
    limit 1
  ) as save_state on true
  left join lateral (
    select r.reaction_type as viewer_vote
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.user_id = auth.uid()
      and r.reaction_type in ('upvote', 'downvote')
    limit 1
  ) as vote_state on true
  left join lateral (
    select true as viewer_marked_helpful
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.user_id = auth.uid()
      and r.reaction_type = 'helpful'
    limit 1
  ) as helpful_state on true
  where auth.uid() is not null
    and public.community_viewer_ready()
    and bu.id is null
    and p.moderation_status = 'clean'
    and p.status <> 'removed'
    and (input_topic_id is null or p.topic_id = input_topic_id)
  order by
    case when tf.user_id is not null then 1 else 0 end desc,
    case when p.status = 'open' then 1 else 0 end desc,
    coalesce(helpful_counts.helpful_count, 0) desc,
    coalesce(comment_counts.comment_count, 0) desc,
    p.created_at desc
  limit greatest(1, least(coalesce(input_limit, 25), 50))
  offset greatest(coalesce(input_offset, 0), 0);
$$;

create or replace function public.get_post_detail(input_post_id uuid)
returns table (
  post_id uuid,
  topic_id uuid,
  topic_name text,
  topic_slug text,
  title text,
  body text,
  post_type text,
  status text,
  is_anonymous boolean,
  created_at timestamptz,
  updated_at timestamptz,
  comment_count bigint,
  helpful_count bigint,
  net_votes bigint,
  viewer_has_saved boolean,
  viewer_vote text,
  viewer_marked_helpful boolean,
  viewer_is_owner boolean,
  author_label text,
  author_trust_hint text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id as post_id,
    t.id as topic_id,
    t.name as topic_name,
    t.slug as topic_slug,
    p.title,
    p.body,
    p.post_type,
    p.status,
    p.is_anonymous,
    p.created_at,
    p.updated_at,
    coalesce(comment_counts.comment_count, 0) as comment_count,
    coalesce(helpful_counts.helpful_count, 0) as helpful_count,
    coalesce(vote_counts.net_votes, 0) as net_votes,
    coalesce(save_state.viewer_has_saved, false) as viewer_has_saved,
    vote_state.viewer_vote,
    coalesce(helpful_state.viewer_marked_helpful, false) as viewer_marked_helpful,
    p.user_id = auth.uid() as viewer_is_owner,
    case
      when p.is_anonymous then 'Anonymous'
      else up.handle
    end as author_label,
    case
      when age(timezone('utc', now()), u.created_at) < interval '30 days' then 'Member since this month'
      else 'Community contributor'
    end as author_trust_hint
  from public.posts p
  join public.topics t
    on t.id = p.topic_id
   and t.is_active = true
  join public.users u
    on u.id = p.user_id
   and u.status = 'active'
  join public.user_profiles up
    on up.user_id = p.user_id
  left join public.blocked_users bu
    on bu.user_id = auth.uid()
   and bu.blocked_user_id = p.user_id
  left join lateral (
    select count(*)::bigint as comment_count
    from public.comments c
    left join public.blocked_users comment_blocks
      on comment_blocks.user_id = auth.uid()
     and comment_blocks.blocked_user_id = c.user_id
    where c.post_id = p.id
      and c.is_deleted = false
      and c.moderation_status = 'clean'
      and comment_blocks.id is null
  ) as comment_counts on true
  left join lateral (
    select count(*)::bigint as helpful_count
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.reaction_type = 'helpful'
  ) as helpful_counts on true
  left join lateral (
    select
      coalesce(sum(case when r.reaction_type = 'upvote' then 1 when r.reaction_type = 'downvote' then -1 else 0 end), 0)::bigint as net_votes
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.reaction_type in ('upvote', 'downvote')
  ) as vote_counts on true
  left join lateral (
    select true as viewer_has_saved
    from public.saves s
    where s.post_id = p.id
      and s.user_id = auth.uid()
    limit 1
  ) as save_state on true
  left join lateral (
    select r.reaction_type as viewer_vote
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.user_id = auth.uid()
      and r.reaction_type in ('upvote', 'downvote')
    limit 1
  ) as vote_state on true
  left join lateral (
    select true as viewer_marked_helpful
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.user_id = auth.uid()
      and r.reaction_type = 'helpful'
    limit 1
  ) as helpful_state on true
  where auth.uid() is not null
    and public.community_viewer_ready()
    and bu.id is null
    and p.id = input_post_id
    and p.moderation_status = 'clean'
    and p.status <> 'removed';
$$;

create or replace function public.get_post_comments(input_post_id uuid)
returns table (
  comment_id uuid,
  parent_comment_id uuid,
  body text,
  created_at timestamptz,
  author_label text,
  author_trust_hint text,
  viewer_is_owner boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    c.id as comment_id,
    c.parent_comment_id,
    c.body,
    c.created_at,
    up.handle as author_label,
    case
      when age(timezone('utc', now()), u.created_at) < interval '30 days' then 'Member since this month'
      else 'Community contributor'
    end as author_trust_hint,
    c.user_id = auth.uid() as viewer_is_owner
  from public.comments c
  join public.posts p
    on p.id = c.post_id
   and p.moderation_status = 'clean'
   and p.status <> 'removed'
  join public.users u
    on u.id = c.user_id
   and u.status = 'active'
  join public.user_profiles up
    on up.user_id = c.user_id
  left join public.blocked_users bu
    on bu.user_id = auth.uid()
   and bu.blocked_user_id = c.user_id
  where auth.uid() is not null
    and public.community_viewer_ready()
    and bu.id is null
    and c.post_id = input_post_id
    and c.is_deleted = false
    and c.moderation_status = 'clean'
  order by c.created_at asc;
$$;

create or replace function public.search_posts(
  input_query text,
  input_topic_id uuid default null,
  input_limit integer default 25
)
returns table (
  post_id uuid,
  topic_id uuid,
  topic_name text,
  topic_slug text,
  title text,
  body_preview text,
  post_type text,
  status text,
  is_anonymous boolean,
  created_at timestamptz,
  comment_count bigint,
  helpful_count bigint,
  net_votes bigint,
  viewer_has_saved boolean,
  viewer_vote text,
  viewer_marked_helpful boolean,
  author_label text,
  author_trust_hint text
)
language sql
stable
security definer
set search_path = public
as $$
  with search_input as (
    select lower(trim(coalesce(input_query, ''))) as query
  )
  select
    p.id as post_id,
    t.id as topic_id,
    t.name as topic_name,
    t.slug as topic_slug,
    p.title,
    case
      when p.body is null or btrim(p.body) = '' then null
      when char_length(btrim(p.body)) <= 220 then btrim(p.body)
      else left(btrim(p.body), 217) || '...'
    end as body_preview,
    p.post_type,
    p.status,
    p.is_anonymous,
    p.created_at,
    coalesce(comment_counts.comment_count, 0) as comment_count,
    coalesce(helpful_counts.helpful_count, 0) as helpful_count,
    coalesce(vote_counts.net_votes, 0) as net_votes,
    coalesce(save_state.viewer_has_saved, false) as viewer_has_saved,
    vote_state.viewer_vote,
    coalesce(helpful_state.viewer_marked_helpful, false) as viewer_marked_helpful,
    case
      when p.is_anonymous then 'Anonymous'
      else up.handle
    end as author_label,
    case
      when age(timezone('utc', now()), u.created_at) < interval '30 days' then 'Member since this month'
      else 'Community contributor'
    end as author_trust_hint
  from search_input q
  join public.posts p on true
  join public.topics t
    on t.id = p.topic_id
   and t.is_active = true
  join public.users u
    on u.id = p.user_id
   and u.status = 'active'
  join public.user_profiles up
    on up.user_id = p.user_id
  left join public.blocked_users bu
    on bu.user_id = auth.uid()
   and bu.blocked_user_id = p.user_id
  left join lateral (
    select count(*)::bigint as comment_count
    from public.comments c
    left join public.blocked_users comment_blocks
      on comment_blocks.user_id = auth.uid()
     and comment_blocks.blocked_user_id = c.user_id
    where c.post_id = p.id
      and c.is_deleted = false
      and c.moderation_status = 'clean'
      and comment_blocks.id is null
  ) as comment_counts on true
  left join lateral (
    select count(*)::bigint as helpful_count
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.reaction_type = 'helpful'
  ) as helpful_counts on true
  left join lateral (
    select
      coalesce(sum(case when r.reaction_type = 'upvote' then 1 when r.reaction_type = 'downvote' then -1 else 0 end), 0)::bigint as net_votes
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.reaction_type in ('upvote', 'downvote')
  ) as vote_counts on true
  left join lateral (
    select true as viewer_has_saved
    from public.saves s
    where s.post_id = p.id
      and s.user_id = auth.uid()
    limit 1
  ) as save_state on true
  left join lateral (
    select r.reaction_type as viewer_vote
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.user_id = auth.uid()
      and r.reaction_type in ('upvote', 'downvote')
    limit 1
  ) as vote_state on true
  left join lateral (
    select true as viewer_marked_helpful
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.user_id = auth.uid()
      and r.reaction_type = 'helpful'
    limit 1
  ) as helpful_state on true
  where auth.uid() is not null
    and public.community_viewer_ready()
    and bu.id is null
    and q.query <> ''
    and p.moderation_status = 'clean'
    and p.status <> 'removed'
    and (input_topic_id is null or p.topic_id = input_topic_id)
    and (
      lower(p.title) like '%' || q.query || '%'
      or lower(coalesce(p.body, '')) like '%' || q.query || '%'
      or lower(t.name) like '%' || q.query || '%'
    )
  order by
    case when lower(p.title) = q.query then 0 else 1 end asc,
    case when lower(p.title) like q.query || '%' then 0 else 1 end asc,
    case when lower(p.title) like '%' || q.query || '%' then 0 else 1 end asc,
    case when lower(coalesce(p.body, '')) like '%' || q.query || '%' then 0 else 1 end asc,
    coalesce(helpful_counts.helpful_count, 0) desc,
    p.created_at desc
  limit greatest(1, least(coalesce(input_limit, 25), 50));
$$;

create or replace function public.report_post(
  input_post_id uuid,
  input_reason text,
  input_details text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_reason text;
  normalized_details text;
  created_report_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  if not public.community_viewer_ready() then
    raise exception 'Complete onboarding before reporting content.';
  end if;

  perform 1
  from public.posts
  where id = input_post_id
    and moderation_status in ('clean', 'flagged', 'under_review')
    and status <> 'removed';

  if not found then
    raise exception 'This post is unavailable.';
  end if;

  normalized_reason := btrim(coalesce(input_reason, ''));
  normalized_details := nullif(btrim(coalesce(input_details, '')), '');

  if char_length(normalized_reason) < 3 or char_length(normalized_reason) > 80 then
    raise exception 'Choose a report reason.';
  end if;

  if normalized_details is not null and char_length(normalized_details) > 1000 then
    raise exception 'Report details must be 1000 characters or fewer.';
  end if;

  insert into public.reports (
    reporter_user_id,
    target_type,
    target_id,
    reason,
    details
  )
  values (
    auth.uid(),
    'post',
    input_post_id,
    normalized_reason,
    normalized_details
  )
  returning id into created_report_id;

  update public.posts
    set moderation_status = case
      when moderation_status = 'clean' then 'flagged'
      else moderation_status
    end
  where id = input_post_id;

  return created_report_id;
end;
$$;

create or replace function public.report_comment(
  input_comment_id uuid,
  input_reason text,
  input_details text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_reason text;
  normalized_details text;
  created_report_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  if not public.community_viewer_ready() then
    raise exception 'Complete onboarding before reporting content.';
  end if;

  perform 1
  from public.comments
  where id = input_comment_id
    and moderation_status in ('clean', 'flagged', 'under_review')
    and is_deleted = false;

  if not found then
    raise exception 'This comment is unavailable.';
  end if;

  normalized_reason := btrim(coalesce(input_reason, ''));
  normalized_details := nullif(btrim(coalesce(input_details, '')), '');

  if char_length(normalized_reason) < 3 or char_length(normalized_reason) > 80 then
    raise exception 'Choose a report reason.';
  end if;

  if normalized_details is not null and char_length(normalized_details) > 1000 then
    raise exception 'Report details must be 1000 characters or fewer.';
  end if;

  insert into public.reports (
    reporter_user_id,
    target_type,
    target_id,
    reason,
    details
  )
  values (
    auth.uid(),
    'comment',
    input_comment_id,
    normalized_reason,
    normalized_details
  )
  returning id into created_report_id;

  update public.comments
    set moderation_status = case
      when moderation_status = 'clean' then 'flagged'
      else moderation_status
    end
  where id = input_comment_id;

  return created_report_id;
end;
$$;

create or replace function public.block_post_author(input_post_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  target_user_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  if not public.community_viewer_ready() then
    raise exception 'Complete onboarding before blocking accounts.';
  end if;

  select user_id
    into target_user_id
  from public.posts
  where id = input_post_id
    and moderation_status in ('clean', 'flagged', 'under_review')
    and status <> 'removed';

  if target_user_id is null then
    raise exception 'This post is unavailable.';
  end if;

  if target_user_id = auth.uid() then
    raise exception 'You cannot block your own account.';
  end if;

  insert into public.blocked_users (user_id, blocked_user_id)
  values (auth.uid(), target_user_id)
  on conflict (user_id, blocked_user_id) do nothing;

  return true;
end;
$$;

create or replace function public.block_comment_author(input_comment_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  target_user_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  if not public.community_viewer_ready() then
    raise exception 'Complete onboarding before blocking accounts.';
  end if;

  select user_id
    into target_user_id
  from public.comments
  where id = input_comment_id
    and moderation_status in ('clean', 'flagged', 'under_review')
    and is_deleted = false;

  if target_user_id is null then
    raise exception 'This comment is unavailable.';
  end if;

  if target_user_id = auth.uid() then
    raise exception 'You cannot block your own account.';
  end if;

  insert into public.blocked_users (user_id, blocked_user_id)
  values (auth.uid(), target_user_id)
  on conflict (user_id, blocked_user_id) do nothing;

  return true;
end;
$$;

revoke all on function public.community_viewer_ready() from public;
revoke all on function public.search_posts(text, uuid, integer) from public;
revoke all on function public.report_post(uuid, text, text) from public;
revoke all on function public.report_comment(uuid, text, text) from public;
revoke all on function public.block_post_author(uuid) from public;
revoke all on function public.block_comment_author(uuid) from public;

grant execute on function public.community_viewer_ready() to authenticated;
grant execute on function public.search_posts(text, uuid, integer) to authenticated;
grant execute on function public.report_post(uuid, text, text) to authenticated;
grant execute on function public.report_comment(uuid, text, text) to authenticated;
grant execute on function public.block_post_author(uuid) to authenticated;
grant execute on function public.block_comment_author(uuid) to authenticated;
-- END MIGRATION: 20260323_000003_search_and_safety.sql

-- BEGIN MIGRATION: 20260323_000004_notifications.sql
create index if not exists notifications_user_created_at_idx
  on public.notifications (user_id, created_at desc);

create index if not exists notifications_user_is_read_created_at_idx
  on public.notifications (user_id, is_read, created_at desc);

create or replace function public.handle_new_comment_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  post_owner_id uuid;
  parent_comment_owner_id uuid;
begin
  select p.user_id
    into post_owner_id
  from public.posts p
  where p.id = new.post_id
    and p.status <> 'removed'
    and p.moderation_status in ('clean', 'flagged', 'under_review');

  if post_owner_id is not null and post_owner_id <> new.user_id then
    insert into public.notifications (user_id, type, entity_type, entity_id)
    values (post_owner_id, 'new_comment', 'comment', new.id);
  end if;

  if new.parent_comment_id is not null then
    select c.user_id
      into parent_comment_owner_id
    from public.comments c
    where c.id = new.parent_comment_id
      and c.is_deleted = false
      and c.moderation_status in ('clean', 'flagged', 'under_review');

    if parent_comment_owner_id is not null
      and parent_comment_owner_id <> new.user_id
      and parent_comment_owner_id <> post_owner_id then
      insert into public.notifications (user_id, type, entity_type, entity_id)
      values (parent_comment_owner_id, 'comment_reply', 'comment', new.id);
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists comments_notify_activity on public.comments;
create trigger comments_notify_activity
after insert on public.comments
for each row
execute procedure public.handle_new_comment_notification();

create or replace function public.handle_new_post_reaction_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  post_owner_id uuid;
  notification_type text;
begin
  if new.target_type <> 'post' or new.reaction_type not in ('upvote', 'helpful') then
    return new;
  end if;

  select p.user_id
    into post_owner_id
  from public.posts p
  where p.id = new.target_id
    and p.status <> 'removed'
    and p.moderation_status in ('clean', 'flagged', 'under_review');

  if post_owner_id is null or post_owner_id = new.user_id then
    return new;
  end if;

  notification_type := case
    when new.reaction_type = 'helpful' then 'post_helpful'
    else 'post_upvote'
  end;

  insert into public.notifications (user_id, type, entity_type, entity_id)
  values (post_owner_id, notification_type, 'reaction', new.id);

  return new;
end;
$$;

drop trigger if exists reactions_notify_activity on public.reactions;
create trigger reactions_notify_activity
after insert on public.reactions
for each row
execute procedure public.handle_new_post_reaction_notification();

create or replace function public.get_notifications(
  input_limit integer default 30,
  input_offset integer default 0,
  input_unread_only boolean default false
)
returns table (
  notification_id uuid,
  notification_type text,
  entity_type text,
  entity_id uuid,
  post_id uuid,
  post_title text,
  actor_label text,
  message_title text,
  message_preview text,
  is_read boolean,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  with scoped_notifications as (
    select
      n.id,
      n.type,
      n.entity_type,
      n.entity_id,
      n.is_read,
      n.created_at,
      case
        when n.entity_type = 'comment' then c.user_id
        when n.entity_type = 'reaction' then r.user_id
        else null
      end as actor_user_id,
      case
        when n.entity_type = 'comment' then c.post_id
        when n.entity_type = 'reaction' and r.target_type = 'post' then r.target_id
        else null
      end as linked_post_id,
      c.body as comment_body,
      p.title as linked_post_title
    from public.notifications n
    left join public.comments c
      on n.entity_type = 'comment'
     and n.entity_id = c.id
     and c.is_deleted = false
     and c.moderation_status in ('clean', 'flagged', 'under_review')
    left join public.reactions r
      on n.entity_type = 'reaction'
     and n.entity_id = r.id
     and r.target_type = 'post'
     and r.reaction_type in ('upvote', 'helpful')
    left join public.posts p
      on (
        (n.entity_type = 'comment' and p.id = c.post_id)
        or (n.entity_type = 'reaction' and r.target_type = 'post' and p.id = r.target_id)
      )
     and p.status <> 'removed'
     and p.moderation_status in ('clean', 'flagged', 'under_review')
    where auth.uid() is not null
      and public.community_viewer_ready()
      and n.user_id = auth.uid()
      and (not input_unread_only or n.is_read = false)
  )
  select
    scoped.id as notification_id,
    scoped.type as notification_type,
    scoped.entity_type,
    scoped.entity_id,
    scoped.linked_post_id as post_id,
    scoped.linked_post_title as post_title,
    coalesce(actor_profile.handle, 'Someone') as actor_label,
    case scoped.type
      when 'new_comment' then coalesce(actor_profile.handle, 'Someone') || ' commented on your post'
      when 'comment_reply' then coalesce(actor_profile.handle, 'Someone') || ' replied to your comment'
      when 'post_helpful' then coalesce(actor_profile.handle, 'Someone') || ' marked your post helpful'
      when 'post_upvote' then coalesce(actor_profile.handle, 'Someone') || ' upvoted your post'
      else 'New activity on your content'
    end as message_title,
    case
      when scoped.type in ('new_comment', 'comment_reply') then
        case
          when scoped.comment_body is null or btrim(scoped.comment_body) = '' then null
          when char_length(btrim(scoped.comment_body)) <= 160 then btrim(scoped.comment_body)
          else left(btrim(scoped.comment_body), 157) || '...'
        end
      when scoped.linked_post_title is not null then
        'On ' || scoped.linked_post_title
      else null
    end as message_preview,
    scoped.is_read,
    scoped.created_at
  from scoped_notifications scoped
  left join public.users actor_user
    on actor_user.id = scoped.actor_user_id
   and actor_user.status = 'active'
  left join public.user_profiles actor_profile
    on actor_profile.user_id = actor_user.id
  left join public.blocked_users bu
    on bu.user_id = auth.uid()
   and bu.blocked_user_id = scoped.actor_user_id
  where bu.id is null
    and scoped.linked_post_id is not null
  order by scoped.created_at desc
  limit greatest(1, least(coalesce(input_limit, 30), 50))
  offset greatest(coalesce(input_offset, 0), 0);
$$;

create or replace function public.get_unread_notification_count()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  with scoped_notifications as (
    select
      n.id,
      case
        when n.entity_type = 'comment' then c.user_id
        when n.entity_type = 'reaction' then r.user_id
        else null
      end as actor_user_id,
      case
        when n.entity_type = 'comment' then c.post_id
        when n.entity_type = 'reaction' and r.target_type = 'post' then r.target_id
        else null
      end as linked_post_id
    from public.notifications n
    left join public.comments c
      on n.entity_type = 'comment'
     and n.entity_id = c.id
     and c.is_deleted = false
     and c.moderation_status in ('clean', 'flagged', 'under_review')
    left join public.reactions r
      on n.entity_type = 'reaction'
     and n.entity_id = r.id
     and r.target_type = 'post'
     and r.reaction_type in ('upvote', 'helpful')
    left join public.posts p
      on (
        (n.entity_type = 'comment' and p.id = c.post_id)
        or (n.entity_type = 'reaction' and r.target_type = 'post' and p.id = r.target_id)
      )
     and p.status <> 'removed'
     and p.moderation_status in ('clean', 'flagged', 'under_review')
    where auth.uid() is not null
      and public.community_viewer_ready()
      and n.user_id = auth.uid()
      and n.is_read = false
      and p.id is not null
  )
  select count(*)::integer
  from scoped_notifications scoped
  left join public.blocked_users bu
    on bu.user_id = auth.uid()
   and bu.blocked_user_id = scoped.actor_user_id
  where bu.id is null
    and scoped.linked_post_id is not null;
$$;

create or replace function public.mark_notification_read(input_notification_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_count integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  if not public.community_viewer_ready() then
    raise exception 'Complete onboarding before viewing notifications.';
  end if;

  update public.notifications
    set is_read = true
  where id = input_notification_id
    and user_id = auth.uid();

  get diagnostics updated_count = row_count;
  return updated_count > 0;
end;
$$;

create or replace function public.mark_all_notifications_read()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_count integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  if not public.community_viewer_ready() then
    raise exception 'Complete onboarding before viewing notifications.';
  end if;

  update public.notifications
    set is_read = true
  where user_id = auth.uid()
    and is_read = false;

  get diagnostics updated_count = row_count;
  return updated_count;
end;
$$;

revoke all on function public.get_notifications(integer, integer, boolean) from public;
revoke all on function public.get_unread_notification_count() from public;
revoke all on function public.mark_notification_read(uuid) from public;
revoke all on function public.mark_all_notifications_read() from public;

grant execute on function public.get_notifications(integer, integer, boolean) to authenticated;
grant execute on function public.get_unread_notification_count() to authenticated;
grant execute on function public.mark_notification_read(uuid) to authenticated;
grant execute on function public.mark_all_notifications_read() to authenticated;
-- END MIGRATION: 20260323_000004_notifications.sql

-- BEGIN MIGRATION: 20260323_000005_moderation_tools.sql
create index if not exists reports_status_created_at_idx
  on public.reports (status, created_at desc);

create index if not exists reports_target_status_idx
  on public.reports (target_type, target_id, status);

create index if not exists moderation_actions_target_created_at_idx
  on public.moderation_actions (target_type, target_id, created_at desc);

create or replace function public.get_moderation_queue(
  input_status text default 'open',
  input_limit integer default 30,
  input_offset integer default 0
)
returns table (
  report_id uuid,
  report_status text,
  report_reason text,
  report_details text,
  reported_at timestamptz,
  target_type text,
  target_id uuid,
  post_id uuid,
  post_title text,
  target_preview text,
  target_author_id uuid,
  target_author_label text,
  target_account_status text,
  reporter_user_id uuid,
  reporter_label text,
  open_reports_for_target bigint,
  target_moderation_status text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    r.id as report_id,
    r.status as report_status,
    r.reason as report_reason,
    r.details as report_details,
    r.created_at as reported_at,
    r.target_type,
    r.target_id,
    case
      when r.target_type = 'post' then p.id
      when r.target_type = 'comment' then cp.id
      else null
    end as post_id,
    case
      when r.target_type = 'post' then p.title
      when r.target_type = 'comment' then cp.title
      else null
    end as post_title,
    case
      when r.target_type = 'post' then
        case
          when p.body is null or btrim(p.body) = '' then null
          when char_length(btrim(p.body)) <= 220 then btrim(p.body)
          else left(btrim(p.body), 217) || '...'
        end
      when r.target_type = 'comment' then
        case
          when c.body is null or btrim(c.body) = '' then null
          when char_length(btrim(c.body)) <= 220 then btrim(c.body)
          else left(btrim(c.body), 217) || '...'
        end
      else null
    end as target_preview,
    coalesce(p.user_id, c.user_id) as target_author_id,
    coalesce(target_profile.handle, 'Unknown user') as target_author_label,
    target_user.status as target_account_status,
    r.reporter_user_id,
    coalesce(reporter_profile.handle, 'Reporter') as reporter_label,
    coalesce(open_reports.open_reports_for_target, 0) as open_reports_for_target,
    case
      when r.target_type = 'post' then p.moderation_status
      when r.target_type = 'comment' then c.moderation_status
      else null
    end as target_moderation_status
  from public.reports r
  left join public.posts p
    on r.target_type = 'post'
   and r.target_id = p.id
  left join public.comments c
    on r.target_type = 'comment'
   and r.target_id = c.id
  left join public.posts cp
    on r.target_type = 'comment'
   and c.post_id = cp.id
  left join public.users target_user
    on target_user.id = coalesce(p.user_id, c.user_id)
  left join public.user_profiles target_profile
    on target_profile.user_id = target_user.id
  left join public.user_profiles reporter_profile
    on reporter_profile.user_id = r.reporter_user_id
  left join lateral (
    select count(*)::bigint as open_reports_for_target
    from public.reports sibling_reports
    where sibling_reports.target_type = r.target_type
      and sibling_reports.target_id = r.target_id
      and sibling_reports.status = 'open'
  ) as open_reports on true
  where auth.uid() is not null
    and public.app_is_staff()
    and (
      coalesce(nullif(lower(trim(input_status)), ''), 'open') = 'all'
      or r.status = coalesce(nullif(lower(trim(input_status)), ''), 'open')
    )
  order by
    case r.status
      when 'open' then 0
      when 'reviewed' then 1
      when 'actioned' then 2
      when 'dismissed' then 3
      else 4
    end asc,
    r.created_at desc
  limit greatest(1, least(coalesce(input_limit, 30), 60))
  offset greatest(coalesce(input_offset, 0), 0);
$$;

create or replace function public.resolve_report(
  input_report_id uuid,
  input_action text,
  input_notes text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_report public.reports%rowtype;
  normalized_action text;
  normalized_notes text;
  target_user_id uuid;
  target_user_role text;
  reviewer_role text;
  remaining_open_reports integer;
begin
  if auth.uid() is null or not public.app_is_staff() then
    raise exception 'Staff access required.';
  end if;

  normalized_action := lower(trim(coalesce(input_action, '')));
  normalized_notes := nullif(trim(coalesce(input_notes, '')), '');

  if normalized_action not in (
    'dismiss',
    'remove_post',
    'lock_post',
    'remove_comment',
    'suspend_author',
    'ban_author'
  ) then
    raise exception 'Choose a valid moderation action.';
  end if;

  select *
    into current_report
  from public.reports
  where id = input_report_id
  for update;

  if not found then
    raise exception 'This report was not found.';
  end if;

  if current_report.status in ('actioned', 'dismissed') then
    raise exception 'This report has already been closed.';
  end if;

  if current_report.target_type = 'post' then
    select p.user_id, u.role
      into target_user_id, target_user_role
    from public.posts p
    join public.users u
      on u.id = p.user_id
    where p.id = current_report.target_id;
  elsif current_report.target_type = 'comment' then
    select c.user_id, u.role
      into target_user_id, target_user_role
    from public.comments c
    join public.users u
      on u.id = c.user_id
    where c.id = current_report.target_id;
  else
    raise exception 'Unsupported report target.';
  end if;

  if target_user_id is null then
    raise exception 'Target content is unavailable.';
  end if;

  select role
    into reviewer_role
  from public.users
  where id = auth.uid();

  if reviewer_role is null then
    raise exception 'Staff account not found.';
  end if;

  if normalized_action in ('suspend_author', 'ban_author') then
    if target_user_id = auth.uid() then
      raise exception 'You cannot moderate your own account.';
    end if;

    if target_user_role in ('moderator', 'admin') and reviewer_role <> 'admin' then
      raise exception 'Only admins can moderate staff accounts.';
    end if;
  end if;

  if normalized_action = 'dismiss' then
    update public.reports
      set status = 'dismissed',
          reviewed_by = auth.uid(),
          reviewed_at = timezone('utc', now())
    where id = current_report.id;

    select count(*)::integer
      into remaining_open_reports
    from public.reports
    where target_type = current_report.target_type
      and target_id = current_report.target_id
      and status = 'open';

    if remaining_open_reports = 0 then
      if current_report.target_type = 'post' then
        update public.posts
          set moderation_status = case
            when moderation_status = 'flagged' then 'clean'
            else moderation_status
          end
        where id = current_report.target_id
          and status <> 'removed';
      else
        update public.comments
          set moderation_status = case
            when moderation_status = 'flagged' then 'clean'
            else moderation_status
          end
        where id = current_report.target_id
          and is_deleted = false;
      end if;
    end if;

    insert into public.moderation_actions (
      moderator_user_id,
      target_type,
      target_id,
      action_type,
      reason,
      notes
    )
    values (
      auth.uid(),
      current_report.target_type,
      current_report.target_id,
      'dismiss_report',
      current_report.reason,
      normalized_notes
    );

    return true;
  end if;

  if normalized_action = 'remove_post' then
    if current_report.target_type <> 'post' then
      raise exception 'This action is only valid for post reports.';
    end if;

    update public.posts
      set moderation_status = 'removed',
          status = 'removed'
    where id = current_report.target_id;

    insert into public.moderation_actions (
      moderator_user_id,
      target_type,
      target_id,
      action_type,
      reason,
      notes
    )
    values (
      auth.uid(),
      'post',
      current_report.target_id,
      'remove_post',
      current_report.reason,
      normalized_notes
    );
  elsif normalized_action = 'lock_post' then
    if current_report.target_type <> 'post' then
      raise exception 'This action is only valid for post reports.';
    end if;

    update public.posts
      set status = 'locked',
          moderation_status = case
            when moderation_status = 'clean' then 'under_review'
            else moderation_status
          end
    where id = current_report.target_id;

    insert into public.moderation_actions (
      moderator_user_id,
      target_type,
      target_id,
      action_type,
      reason,
      notes
    )
    values (
      auth.uid(),
      'post',
      current_report.target_id,
      'lock_post',
      current_report.reason,
      normalized_notes
    );
  elsif normalized_action = 'remove_comment' then
    if current_report.target_type <> 'comment' then
      raise exception 'This action is only valid for comment reports.';
    end if;

    update public.comments
      set is_deleted = true,
          moderation_status = 'removed'
    where id = current_report.target_id;

    insert into public.moderation_actions (
      moderator_user_id,
      target_type,
      target_id,
      action_type,
      reason,
      notes
    )
    values (
      auth.uid(),
      'comment',
      current_report.target_id,
      'remove_comment',
      current_report.reason,
      normalized_notes
    );
  elsif normalized_action = 'suspend_author' then
    update public.users
      set status = 'suspended'
    where id = target_user_id
      and status <> 'banned';

    insert into public.moderation_actions (
      moderator_user_id,
      target_type,
      target_id,
      action_type,
      reason,
      notes
    )
    values (
      auth.uid(),
      'user',
      target_user_id,
      'suspend_author',
      current_report.reason,
      normalized_notes
    );
  elsif normalized_action = 'ban_author' then
    update public.users
      set status = 'banned'
    where id = target_user_id;

    update public.posts
      set moderation_status = 'removed',
          status = 'removed'
    where user_id = target_user_id
      and status <> 'removed';

    update public.comments
      set is_deleted = true,
          moderation_status = 'removed'
    where user_id = target_user_id
      and is_deleted = false;

    insert into public.moderation_actions (
      moderator_user_id,
      target_type,
      target_id,
      action_type,
      reason,
      notes
    )
    values (
      auth.uid(),
      'user',
      target_user_id,
      'ban_author',
      current_report.reason,
      normalized_notes
    );
  end if;

  update public.reports
    set status = 'actioned',
        reviewed_by = auth.uid(),
        reviewed_at = timezone('utc', now())
  where target_type = current_report.target_type
    and target_id = current_report.target_id
    and status in ('open', 'reviewed');

  return true;
end;
$$;

revoke all on function public.get_moderation_queue(text, integer, integer) from public;
revoke all on function public.resolve_report(uuid, text, text) from public;

grant execute on function public.get_moderation_queue(text, integer, integer) to authenticated;
grant execute on function public.resolve_report(uuid, text, text) to authenticated;
-- END MIGRATION: 20260323_000005_moderation_tools.sql

-- BEGIN MIGRATION: 20260323_000006_personal_activity.sql
create or replace function public.get_saved_posts(
  input_limit integer default 20,
  input_offset integer default 0
)
returns table (
  post_id uuid,
  topic_id uuid,
  topic_name text,
  topic_slug text,
  title text,
  body_preview text,
  post_type text,
  status text,
  moderation_status text,
  is_anonymous boolean,
  created_at timestamptz,
  updated_at timestamptz,
  saved_at timestamptz,
  comment_count bigint,
  helpful_count bigint,
  net_votes bigint,
  viewer_has_saved boolean,
  viewer_vote text,
  viewer_marked_helpful boolean,
  author_label text,
  author_trust_hint text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id as post_id,
    t.id as topic_id,
    t.name as topic_name,
    t.slug as topic_slug,
    p.title,
    case
      when p.body is null or btrim(p.body) = '' then null
      when char_length(btrim(p.body)) <= 220 then btrim(p.body)
      else left(btrim(p.body), 217) || '...'
    end as body_preview,
    p.post_type,
    p.status,
    p.moderation_status,
    p.is_anonymous,
    p.created_at,
    p.updated_at,
    s.created_at as saved_at,
    coalesce(comment_counts.comment_count, 0) as comment_count,
    coalesce(helpful_counts.helpful_count, 0) as helpful_count,
    coalesce(vote_counts.net_votes, 0) as net_votes,
    true as viewer_has_saved,
    vote_state.viewer_vote,
    coalesce(helpful_state.viewer_marked_helpful, false) as viewer_marked_helpful,
    case
      when p.is_anonymous then 'Anonymous'
      else up.handle
    end as author_label,
    case
      when age(timezone('utc', now()), u.created_at) < interval '30 days' then 'Member since this month'
      else 'Community contributor'
    end as author_trust_hint
  from public.saves s
  join public.posts p
    on p.id = s.post_id
   and p.moderation_status = 'clean'
   and p.status <> 'removed'
  join public.topics t
    on t.id = p.topic_id
   and t.is_active = true
  join public.users u
    on u.id = p.user_id
   and u.status = 'active'
  join public.user_profiles up
    on up.user_id = p.user_id
  left join public.blocked_users bu
    on bu.user_id = auth.uid()
   and bu.blocked_user_id = p.user_id
  left join lateral (
    select count(*)::bigint as comment_count
    from public.comments c
    left join public.blocked_users comment_blocks
      on comment_blocks.user_id = auth.uid()
     and comment_blocks.blocked_user_id = c.user_id
    where c.post_id = p.id
      and c.is_deleted = false
      and c.moderation_status = 'clean'
      and comment_blocks.id is null
  ) as comment_counts on true
  left join lateral (
    select count(*)::bigint as helpful_count
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.reaction_type = 'helpful'
  ) as helpful_counts on true
  left join lateral (
    select
      coalesce(sum(case when r.reaction_type = 'upvote' then 1 when r.reaction_type = 'downvote' then -1 else 0 end), 0)::bigint as net_votes
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.reaction_type in ('upvote', 'downvote')
  ) as vote_counts on true
  left join lateral (
    select r.reaction_type as viewer_vote
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.user_id = auth.uid()
      and r.reaction_type in ('upvote', 'downvote')
    limit 1
  ) as vote_state on true
  left join lateral (
    select true as viewer_marked_helpful
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.user_id = auth.uid()
      and r.reaction_type = 'helpful'
    limit 1
  ) as helpful_state on true
  where auth.uid() is not null
    and public.community_viewer_ready()
    and s.user_id = auth.uid()
    and bu.id is null
  order by s.created_at desc
  limit greatest(1, least(coalesce(input_limit, 20), 50))
  offset greatest(coalesce(input_offset, 0), 0);
$$;

create or replace function public.get_my_posts(
  input_limit integer default 20,
  input_offset integer default 0
)
returns table (
  post_id uuid,
  topic_id uuid,
  topic_name text,
  topic_slug text,
  title text,
  body_preview text,
  post_type text,
  status text,
  moderation_status text,
  is_anonymous boolean,
  created_at timestamptz,
  updated_at timestamptz,
  saved_at timestamptz,
  comment_count bigint,
  helpful_count bigint,
  net_votes bigint,
  viewer_has_saved boolean,
  viewer_vote text,
  viewer_marked_helpful boolean,
  author_label text,
  author_trust_hint text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id as post_id,
    t.id as topic_id,
    t.name as topic_name,
    t.slug as topic_slug,
    p.title,
    case
      when p.body is null or btrim(p.body) = '' then null
      when char_length(btrim(p.body)) <= 220 then btrim(p.body)
      else left(btrim(p.body), 217) || '...'
    end as body_preview,
    p.post_type,
    p.status,
    p.moderation_status,
    p.is_anonymous,
    p.created_at,
    p.updated_at,
    null::timestamptz as saved_at,
    coalesce(comment_counts.comment_count, 0) as comment_count,
    coalesce(helpful_counts.helpful_count, 0) as helpful_count,
    coalesce(vote_counts.net_votes, 0) as net_votes,
    coalesce(save_state.viewer_has_saved, false) as viewer_has_saved,
    vote_state.viewer_vote,
    coalesce(helpful_state.viewer_marked_helpful, false) as viewer_marked_helpful,
    case
      when p.is_anonymous then 'Anonymous'
      else up.handle
    end as author_label,
    case
      when age(timezone('utc', now()), u.created_at) < interval '30 days' then 'Member since this month'
      else 'Community contributor'
    end as author_trust_hint
  from public.posts p
  join public.topics t
    on t.id = p.topic_id
   and t.is_active = true
  join public.users u
    on u.id = p.user_id
   and u.status in ('active', 'suspended', 'banned')
  join public.user_profiles up
    on up.user_id = p.user_id
  left join lateral (
    select count(*)::bigint as comment_count
    from public.comments c
    where c.post_id = p.id
      and c.is_deleted = false
      and c.moderation_status = 'clean'
  ) as comment_counts on true
  left join lateral (
    select count(*)::bigint as helpful_count
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.reaction_type = 'helpful'
  ) as helpful_counts on true
  left join lateral (
    select
      coalesce(sum(case when r.reaction_type = 'upvote' then 1 when r.reaction_type = 'downvote' then -1 else 0 end), 0)::bigint as net_votes
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.reaction_type in ('upvote', 'downvote')
  ) as vote_counts on true
  left join lateral (
    select true as viewer_has_saved
    from public.saves s
    where s.post_id = p.id
      and s.user_id = auth.uid()
    limit 1
  ) as save_state on true
  left join lateral (
    select r.reaction_type as viewer_vote
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.user_id = auth.uid()
      and r.reaction_type in ('upvote', 'downvote')
    limit 1
  ) as vote_state on true
  left join lateral (
    select true as viewer_marked_helpful
    from public.reactions r
    where r.target_type = 'post'
      and r.target_id = p.id
      and r.user_id = auth.uid()
      and r.reaction_type = 'helpful'
    limit 1
  ) as helpful_state on true
  where auth.uid() is not null
    and public.community_viewer_ready()
    and p.user_id = auth.uid()
  order by p.created_at desc
  limit greatest(1, least(coalesce(input_limit, 20), 50))
  offset greatest(coalesce(input_offset, 0), 0);
$$;

revoke all on function public.get_saved_posts(integer, integer) from public;
revoke all on function public.get_my_posts(integer, integer) from public;

grant execute on function public.get_saved_posts(integer, integer) to authenticated;
grant execute on function public.get_my_posts(integer, integer) to authenticated;
-- END MIGRATION: 20260323_000006_personal_activity.sql

-- BEGIN MIGRATION: 20260323_000007_post_resolution.sql
create or replace function public.create_comment(
  input_post_id uuid,
  input_body text,
  input_parent_comment_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_body text;
  inserted_comment_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  if not public.community_viewer_ready() then
    raise exception 'Complete onboarding before commenting.';
  end if;

  perform 1
  from public.posts
  where id = input_post_id
    and moderation_status = 'clean'
    and status in ('open', 'resolved');

  if not found then
    raise exception 'This post is unavailable for replies.';
  end if;

  if input_parent_comment_id is not null then
    perform 1
    from public.comments
    where id = input_parent_comment_id
      and post_id = input_post_id
      and is_deleted = false
      and moderation_status = 'clean';

    if not found then
      raise exception 'Parent comment is unavailable.';
    end if;
  end if;

  normalized_body := btrim(coalesce(input_body, ''));

  if char_length(normalized_body) = 0 or char_length(normalized_body) > 5000 then
    raise exception 'Comment must be between 1 and 5000 characters.';
  end if;

  insert into public.comments (
    post_id,
    user_id,
    parent_comment_id,
    body
  )
  values (
    input_post_id,
    auth.uid(),
    input_parent_comment_id,
    normalized_body
  )
  returning id into inserted_comment_id;

  return inserted_comment_id;
end;
$$;

create or replace function public.set_my_post_status(
  input_post_id uuid,
  input_status text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_status text;
  current_post public.posts%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  if not public.community_viewer_ready() then
    raise exception 'Complete onboarding before updating your post.';
  end if;

  normalized_status := lower(trim(coalesce(input_status, '')));

  if normalized_status not in ('open', 'resolved') then
    raise exception 'Choose open or resolved.';
  end if;

  select *
    into current_post
  from public.posts
  where id = input_post_id
    and user_id = auth.uid()
  for update;

  if not found then
    raise exception 'That post could not be found.';
  end if;

  if current_post.status = 'removed' or current_post.moderation_status = 'removed' then
    raise exception 'Removed posts cannot be updated.';
  end if;

  if current_post.status = 'locked' then
    raise exception 'This post is locked and cannot be changed.';
  end if;

  if current_post.status = normalized_status then
    return current_post.status;
  end if;

  update public.posts
    set status = normalized_status
  where id = current_post.id;

  return normalized_status;
end;
$$;

revoke all on function public.set_my_post_status(uuid, text) from public;

grant execute on function public.set_my_post_status(uuid, text) to authenticated;
-- END MIGRATION: 20260323_000007_post_resolution.sql

-- BEGIN MIGRATION: 20260327_000008_account_deletion.sql
create or replace function public.delete_my_account()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_role text;
  deleted_count integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  select role
    into current_role
  from public.users
  where id = auth.uid();

  if coalesce(current_role, 'user') in ('moderator', 'admin') then
    raise exception 'Staff accounts require support-assisted deletion so moderation audit trails are preserved.';
  end if;

  delete from auth.users
  where id = auth.uid();

  get diagnostics deleted_count = row_count;

  if deleted_count = 0 then
    raise exception 'Account deletion could not find the signed-in user.';
  end if;

  return true;
end;
$$;

revoke all on function public.delete_my_account() from public;
grant execute on function public.delete_my_account() to authenticated;
-- END MIGRATION: 20260327_000008_account_deletion.sql
